apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      httpMethod: POST

  - name: EDF PostgreSQL
    uid: edf-postgres
    type: postgres
    url: postgres:5432
    database: edf_dw
    user: edf
    secureJsonData:
      password: edf123
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      postgresVersion: 1600
      timescaledb: false
      connMaxLifetime: 14400
